In [55]:
import sys
import pandas as pd
import numpy as np


raw_data = pd.read_csv("../data/TBI PUD 10-08-2013.csv")

In [56]:
print(raw_data.head())
print(raw_data.shape)

   PatNum  EmplType  Certification  InjuryMech  High_impact_InjSev  \
0       1       3.0              3        11.0                 2.0
1       2       5.0              3         8.0                 2.0
2       3       5.0              3         5.0                 2.0
3       4       5.0              3         6.0                 1.0
4       5       3.0              3        12.0                 2.0

   Amnesia_verb  LOCSeparate  LocLen  Seiz  SeizOccur  ...  Finding20  \
0           0.0          0.0    92.0   0.0       92.0  ...         92
1           0.0          0.0    92.0   0.0       92.0  ...          0
2           NaN          NaN    92.0   NaN       92.0  ...          0
3          91.0          0.0    92.0   0.0       92.0  ...         92
4          91.0          0.0    92.0   0.0       92.0  ...          0

   Finding21  Finding22  Finding23  DeathTBI  HospHead  HospHeadPosCT  \
0         92         92         92       0.0       0.0              0
1          0          0          0       0.0       0.0              0
2          0          0          0       0.0       1.0              0
3         92         92         92       0.0       0.0              0
4          0          0          0       0.0       0.0              0

   Intub24Head  Neurosurgery  PosIntFinal
0          0.0           0.0          0.0
1          0.0           0.0          0.0
2          0.0           0.0          0.0
3          0.0           0.0          0.0
4          0.0           0.0          0.0

[5 rows x 125 columns]
(43399, 125)

In [57]:
test_size = 0.2

columns_to_keep = {
    "PatNum": "patient_id",
    "InjuryMech": "injury_mechanism",
    "High_impact_InjSev": "injury_mechanism_severity",
    "Amnesia_verb": "amnesia",
    "LOCSeparate": "loss_of_consciousness",
    "LocLen": "duration_of_loss_of_consciousness",
    "Seiz": "seizure",
    "SeizOccur": "seizure_occurred_time",
    "SeizLen": "seizure_duration",
    "ActNorm": "acting_normally",
    "HA_verb": "headache",
    "HASeverity": "headache_severity",
    "HAStart": "headache_start_time",
    "Vomit": "vomiting",
    "VomitNbr": "number_of_vomiting_episodes",
    "VomitStart": "vomiting_start_time",
    "VomitLast": "vomiting_last_time",
    "Dizzy": "dizziness",
    "GCSEye": "gcs_eye",
    "GCSVerbal": "gcs_verbal",
    "GCSMotor": "gcs_motor",
    "GCSTotal": "gcs_total",
    "AMS": "altered_mental_status",
    "AMSAgitated": "ams_agitated",
    "AMSSleep": "ams_sleep",
    "AMSSlow": "ams_slow",
    "AMSRepeat": "ams_repeat",
    "AMSOth": "ams_other",
    "SFxPalp": "palpable_skull_fracture",
    "SFxPalpDepress": "palpable_skull_fracture_depressed",
    "SFxBas": "basilar_skull_fracture",
    "SFxBasHem": "basilar_skull_fracture_hemotympanum",
    "SFxBasOto": "basilar_skull_fracture_otorrhea",
    "SFxBasPer": "basilar_skull_fracture_periorbital_ecchymosis",
    "SFxBasRet": "basilar_skull_fracture_retroauricular_ecchymosis",
    "SFxBasRhi": "basilar_skull_fracture_rhinorrhea",
    "Hema": "hematoma",
    "HemaLoc": "hematoma_location",
    "HemaSize": "hematoma_size",
    "AgeInMonth": "age_in_months",
    "Gender": "gender",
    "Ethnicity": "ethnicity",
    "Race": "race",
    "PosIntFinal": "clinically_important_tbi",
    "HospHeadPosCT": "ciTBI_1",
    "Intub24Head": "ciTBI_2",
    "Neurosurgery": "ciTBI_3",
    "DeathTBI": "ciTBI_4",
    }

In [58]:
raw_data

,PatNum,EmplType,Certification,InjuryMech,High_impact_InjSev,Amnesia_verb,LOCSeparate,LocLen,Seiz,SeizOccur,...,Finding20,Finding21,Finding22,Finding23,DeathTBI,HospHead,HospHeadPosCT,Intub24Head,Neurosurgery,PosIntFinal
0,1,3.0,3,11.0,2.0,0.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
1,2,5.0,3,8.0,2.0,0.0,0.0,92.0,0.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0
2,3,5.0,3,5.0,2.0,NaN,NaN,92.0,NaN,92.0,...,0,0,0,0,0.0,1.0,0,0.0,0.0,0.0
3,4,5.0,3,6.0,1.0,91.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
4,5,3.0,3,12.0,2.0,91.0,0.0,92.0,0.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43394,43395,5.0,3,8.0,2.0,0.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
43395,43396,5.0,3,6.0,1.0,91.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
43396,43397,5.0,3,7.0,1.0,0.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
43397,43398,5.0,1,8.0,2.0,0.0,0.0,92.0,0.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
43398,43399,5.0,90,8.0,3.0,0.0,0.0,92.0,0.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0

In [59]:
print(raw_data.shape)
df = raw_data
df = df[list(columns_to_keep.keys())]  # only keep relevant columns
df.rename(columns=columns_to_keep, inplace=True)  # rename columns


df = df[df["gcs_total"] >= 14]  # only keep rows with GCS score 14 and 15
df["palpable_skull_fracture"] = df["palpable_skull_fracture"].replace({2: 1})  # combine unclear and palpable skull fracture into one value as that is what the domain knowledge experts did

df.shape

(43399, 125)

(42430, 48)

In [ ]:
df[["gcs_eye", "gcs_verbal", "gcs_motor"]].isna().any(axis=1).sum()

In [ ]:
df["duration_of_loss_of_consciousness"].value_counts()

In [ ]:
df

In [ ]:
# recode 92 (not applicable) to 0 only when loss_of_consciousness = No
df.loc[(df["loss_of_consciousness"] == 0) & (df["duration_of_loss_of_consciousness"] == 92), "duration_of_loss_of_consciousness"] = 0
# recode all remaining 92s to Nan
df.loc[df["duration_of_loss_of_consciousness"] == 92, "duration_of_loss_of_consciousness"] = np.nan

In [ ]:
df[
    (df["clinically_important_tbi"] == 1) &
    
    (
        (df["ciTBI_1"] == 1) &
        (df["ciTBI_2"] == 0) &
        (df["ciTBI_3"] == 0) &
        (df["ciTBI_4"] == 0)    )
]

In [ ]:
df[
    (df["hematoma"] == 1) &
    
    (
        (df["hematoma_location"] == 92)
    )
]

In [60]:
df[
    (df["loss_of_consciousness"] == 0) &
    (df["duration_of_loss_of_consciousness"] != 92)
]

Empty DataFrame
Columns: [patient_id, injury_mechanism, injury_mechanism_severity, amnesia, loss_of_consciousness, duration_of_loss_of_consciousness, seizure, seizure_occurred_time, seizure_duration, acting_normally, headache, headache_severity, headache_start_time, vomiting, number_of_vomiting_episodes, vomiting_start_time, vomiting_last_time, dizziness, gcs_eye, gcs_verbal, gcs_motor, gcs_total, altered_mental_status, ams_agitated, ams_sleep, ams_slow, ams_repeat, ams_other, palpable_skull_fracture, palpable_skull_fracture_depressed, basilar_skull_fracture, basilar_skull_fracture_hemotympanum, basilar_skull_fracture_otorrhea, basilar_skull_fracture_periorbital_ecchymosis, basilar_skull_fracture_retroauricular_ecchymosis, basilar_skull_fracture_rhinorrhea, hematoma, hematoma_location, hematoma_size, age_in_months, gender, ethnicity, race, clinically_important_tbi, ciTBI_1, ciTBI_2, ciTBI_3, ciTBI_4]
Index: []

[0 rows x 48 columns]

In [ ]:
df["duration_of_loss_of_consciousness"].value_counts()